package com.github.doandadr.petualanganhijaiyah.asset

import com.badlogic.gdx.assets.AssetDescriptor
import com.badlogic.gdx.audio.Music
import com.badlogic.gdx.audio.Sound
import com.badlogic.gdx.graphics.Texture
import com.badlogic.gdx.graphics.g2d.TextureAtlas

enum class SoundAsset(
    fileName: String,
    val volume: Float = 1f,
    directory: String = "audio/sound",
    val descriptor: AssetDescriptor<Sound> = AssetDescriptor("$directory/$fileName", Sound::class.java)
) {
    CLICK_BUTTON("button-click.ogg"),
    COIN_TRING("coin.ogg"),
    COMPLETE("complete-chime.ogg"),
    CORRECT_DING("correct.ogg"),
    CORRECT_BLING("correct-2.ogg"),
    INCORRECT("incorrect.ogg"),
    CLICK_MOUSE("mouse-click.ogg"),
    FAILURE("negative-beeps.ogg"),
    POP_LOW("plop.ogg", 0.5f),
    POP_HIGH("pop.ogg", 0.5f),
    STRETCH("pull-stretch.ogg"),
    DRAW_HEAVY("draw.ogg"),
    DRAW_LIGHT("scribble.ogg"),
    CHEER_BIG("crowd-cheer.ogg"),
    CHEER_SMALL("small-crowd.ogg"),
    CHIME_HALF("up-chime-1.ogg"),
    CHIME_FULL("up-chime-2.ogg"),
    CHIME_HIGH("up-chime-4.ogg"),
    FANFARE_ORCHESTRA("fanfare-1.ogg"),
    FANFARE_TADA("fanfare-2.ogg"),
    INCORRECT_BIG("incorrect-big.ogg"),
    LEVEL_SELECT("level-select.ogg"),
    MAX_HIGH("max-1.ogg"),
    MAX_LOW("max-2.ogg"),
    MIN_HIGH("min-1.ogg"),
    MIN_LOW("min-2.ogg"),
    PICK("pickup.ogg"),
    QUESTION("question.ogg"),
    TOUCH("touch.ogg"),
    CANCEL("cancel.ogg"),
    CONFIRM_1("confirm-1.ogg"),
    CONFIRM_2("confirm-2.ogg"),
    DROP("drop.ogg"),
    V01_ALIF("v01-alif.ogg"),
    V02_BA("v02-ba.ogg"),
    V03_TA("v03-ta.ogg"),
    V04_TSA("v04-tsa.ogg"),
    V05_JIM("v05-jim.ogg"),
    V06_KHA("v06-kha.ogg"),
    V07_KHO("v07-kho.ogg"),
    V08_DAL("v08-dal.ogg"),
    V09_DZAL("v09-dzal.ogg"),
    V10_RA("v10-ra.ogg"),
    V11_ZA("v11-za.ogg"),
    V12_SIN("v12-sin.ogg"),
    V13_SYIN("v13-syin.ogg"),
    V14_SHOD("v14-shod.ogg"),
    V15_DHOD("v15-dhod.ogg"),
    V16_THO("v16-tho.ogg"),
    V17_DHO("v17-dho.ogg"),
    V18_AIN("v18-ain.ogg"),
    V19_GHOIN("v19-ghoin.ogg"),
    V20_FA("v20-fa.ogg"),
    V21_QOF("v21-qof.ogg"),
    V22_KAF("v22-kaf.ogg"),
    V23_LAM("v23-lam.ogg"),
    V24_MIM("v24-mim.ogg"),
    V25_NUN("v25-nun.ogg"),
    V26_WAWU("v26-wawu.ogg"),
    V27_HA("v27-ha.ogg"),
    V28_YA("v28-ya.ogg"),
    V29_LAMALIF("v29-lamalif.ogg"),
    V30_HAMZAH("v30-hamzah.ogg"),
}

enum class MusicAsset(
    fileName: String,
    directory: String = "audio/music",
    val volume: Float = 0.5f,
    val descriptor: AssetDescriptor<Music> = AssetDescriptor("$directory/$fileName", Music::class.java)
) {
    DESERT("desert.mp3"),
    DESERT_ALT("desert-2.mp3"),
    FIELD("forest.mp3"),
    HOME("home.mp3"),
    MAP("map.mp3"),
    SNOW("snow.mp3"),
    VICTORY("victory.mp3"),
}

enum class TextureAsset(
    fileName:String,
    directory: String = "graphics/bg",
    val descriptor: AssetDescriptor<Texture> = AssetDescriptor("$directory/$fileName", Texture::class.java)
) {
    DESERT("bg-desert.png"),
    FIELD("bg-field.png"),
    FINISH("bg-finish.png"),
    HOME("bg-home.png"),
    HOME_DIM("bg-home-dim.png"),
    STAGE("bg-stage.png"),
    START("bg-start.png"),
    MAP("bg-map.png"),
    SPOOKY_1("bg-spooky1.jpg"),
    SPOOKY_2("bg-spooky2.jpg"),
    FOREST_1("bg-forest1.jpg"),
    FOREST_2("bg-forest2.jpg"),
    DESERT_1("bg-desert1.jpg"),
    DESERT_2("bg-desert2.jpg"),
    SNOW_1("bg-snow1.jpg"),
    SNOW_2("bg-snow2.jpg"),
    MOUNTAIN_1("bg-mountain1.jpg"),
    MOUNTAIN_2("bg-mountain2.jpg"),
    WOODEN_FRAME("bg-wooden-frame.png")
}

enum class TextureAtlasAsset(
    fileName: String,
    directory: String = "graphics/atlas",
    val descriptor: AssetDescriptor<TextureAtlas> = AssetDescriptor("$directory/$fileName", TextureAtlas::class.java)
) {
    DRAWABLE("drawable.atlas"),
    NINEPATCH("ninepatch.atlas"),
    HIJAIYAH("hijaiyah.atlas"),
}

enum class HijaiyahRegion(
    val region: String
) {
    F01_ALIF("f01-alif.png"),
    F02_BA("f02-ba.png"),
    F03_TA("f03-ta.png"),
    F04_TSA("f04-tsa.png"),
    F05_JIM("f05-jim.png"),
    F06_KHA("f06-kha.png"),
    F07_KHO("f07-kho.png"),
    F08_DAL("f08-dal.png"),
    F09_DZAL("f09-dzal.png"),
    F10_RA("f10-ra.png"),
    F11_ZA("f11-za.png"),
    F12_SIN("f12-sin.png"),
    F13_SYIN("f13-syin.png"),
    F14_SHOD("f14-shod.png"),
    F15_DHOD("f15-dhod.png"),
    F16_THO("f16-tho.png"),
    F17_DHO("f17-dho.png"),
    F18_AIN("f18-ain.png"),
    F19_GHOIN("f19-ghoin.png"),
    F20_FA("f20-fa.png"),
    F21_QOF("f21-qof.png"),
    F22_KAF("f22-kaf.png"),
    F23_LAM("f23-lam.png"),
    F24_MIM("f24-mim.png"),
    F25_NUN("f25-nun.png"),
    F26_WAWU("f26-wawu.png"),
    F27_HA("f27-ha.png"),
    F28_YA("f28-ya.png"),
}

// TODO delete if unused. not updated
enum class DrawableRegion(
    val region: String,
) {
    BACK("back"),
    BOARD("board"),
    BOOK("book"),
    BOY("boy"),
    BOY_SELECT("boy-select"),
    CHECKERED_FLAG("checkered-flag"),
    CIRCLE_G("circle-g"),
    CIRCLE_GW("circle-gw"),
    CIRCLE_Y("circle-y"),
    CIRCLE_YW("circle-yw"),
    COIN("coin"),
    CONFETTI("confetti"),
    GIRL("girl"),
    GIRL_SELECT("girl-select"),
    HAND_POINTING("hand-pointing"),
    ICON_VOLUME("icon-volume"),
    L01_ROCK_BOULDER("l01-rock-boulder"),
    L02_STONES_PLANT("l02-stones-plant"),
    L03_CAT_BIGROCK("l03-cat-bigrock"),
    L04_GRASS_TWIG("l04-grass-twig"),
    L05_POND("l05-pond"),
    L06_BIGSTONE("l06-bigstone"),
    L07_ROCK_PLANTS("l07-rock-plants"),
    L08_CLIFF("l08-cliff"),
    L09_CACTUS_STONE("l09-cactus-stone"),
    LEFT("left"),
    LINE("line"),
    MAGNIFIER("magnifier"),
    RIGHT("right"),
    SALUTE("salute"),
    SIGN("sign"),
    SIGN_SHARP("sign-sharp"),
    SLIDER_KNOB_G("slider-knob-g"),
    SMALL_FIREWORK("small-firework"),
    SPEECH_BUBBLE("speech-bubble"),
    WOOD_SCROLL("wood-scroll"),
}
