package com.github.doandadr.petualanganhijaiyah.asset
import com.github.doandadr.petualanganhijaiyah.asset.Hijaiyah.*

enum class HijaiyahJoined(
    val image: String,
    val answer: Array<Hijaiyah>,
    val option1: Array<Hijaiyah>,
    val option2: Array<Hijaiyah>,
) {
    J01_A_JA_LA("j01-'a-ja-la", arrayOf(AIN, JIM, LAM), arrayOf(ALIF, KHA, RA), arrayOf(GHOIN, KHO, RA)),
    J02_A_KA_LA("j02-a-ka-la", arrayOf(ALIF, KAF, LAM), arrayOf(ALIF, KHA, RA), arrayOf(AIN, DAL, LAM)),
    J03_A_NA_QA("j03-'a-na-qa", arrayOf(AIN, NUN, QOF), arrayOf(GHOIN, TSA, FA), arrayOf(GHOIN, NUN, FA)),
    J04_A_QA_MA("j04-'a-qa-ma", arrayOf(AIN, QOF, MIM), arrayOf(GHOIN, FA, HA), arrayOf(AIN, TA, MIM)),
    J05_BA_A_DA("j05-ba-'a-da", arrayOf(BA, AIN, DAL), arrayOf(NUN, GHOIN, DZAL), arrayOf(TA, AIN, RA)),
    J06_BA_A_TA("j06-ba-a-ta", arrayOf(BA, ALIF, TA), arrayOf(TSA, ALIF, TSA), arrayOf(BA, AIN, TSA)),
    J07_BA_A_YA("j07-ba-a-ya", arrayOf(BA, ALIF, YA), arrayOf(YA, ALIF, RA), arrayOf(BA, ALIF, RA)),
    J08_BA_WA("j08-ba-wa", arrayOf(BA, WAWU), arrayOf(TA, QOF), arrayOf(YA, FA)),
    J09_DHA_FA("j09-dha-fa", arrayOf(DHOD, FA), arrayOf(DHOD, WAWU), arrayOf(DHO, FA)),
    J10_DHA_KHA_KA("j10-dha-kha-ka", arrayOf(DHOD, KHA, KAF), arrayOf(DHOD, KHA, LAM), arrayOf(DHO, KHO, ALIF)),
    J11_DHA_KHA_MA("j11-dha-kha-ma", arrayOf(DHOD, KHA, MIM), arrayOf(DHOD, JIM, HA), arrayOf(SYIN, KHO, RA)),
    J12_DZA_HA_BA("j12-dza-ha-ba", arrayOf(DZAL, HA, BA), arrayOf(DZAL, AIN, YA), arrayOf(NUN, HA, JIM)),
    J13_FA_RA_SYA("j13-fa-ra-sya", arrayOf(FA, RA, SYIN), arrayOf(FA, ZA, SIN), arrayOf(KHO, RA, TSA)),
    J14_FA_TA_RA("j14-fa-ta-ra", arrayOf(FA, TA, RA), arrayOf(FA, TSA, ZA), arrayOf(NUN, TA, YA)),
    J15_FA_TA_YA("j15-fa-ta-ya", arrayOf(FA, TA, YA), arrayOf(QOF, YA, TA), arrayOf(FA, NUN, ZA)),
    J16_GHA_FA_LA_A("j16-gha-fa-la-a", arrayOf(GHOIN, FA, LAM, ALIF), arrayOf(GHOIN, FA, KAF), arrayOf(KHO, NUN, ALIF, ALIF)),
    J17_GHA_SA_QA("j17-gha-sa-qa", arrayOf(GHOIN, SIN, QOF), arrayOf(GHOIN, SYIN, FA), arrayOf(JIM, SIN, TA)),
    J18_GHA_WA("j18-gha-wa", arrayOf(GHOIN, WAWU), arrayOf(AIN, QOF), arrayOf(JIM, RA)),
    J19_GHA_YA_ZA("j19-gha-ya-za", arrayOf(GHOIN, YA, ZA), arrayOf(AIN, BA, RA), arrayOf(KHO, YA, ZA)),
    J20_HA_KA_DZA("j20-ha-ka-dza", arrayOf(HA, KAF, DZAL), arrayOf(AIN, KAF, ZA), arrayOf(MIM, LAM, DZAL)),
    J21_JA_ZA_A("j21-ja-za-'a", arrayOf(JIM, ZA, AIN), arrayOf(JIM, ZA, JIM), arrayOf(BA, NUN, AIN)),
    J22_KHO_TA_MA("j22-kho-ta-ma", arrayOf(KHO, TA, MIM), arrayOf(NUN, TA, RA), arrayOf(NUN, YA, MIM)),
    J23_LA_A("j23-la-a", arrayOf(LAM, ALIF), arrayOf(RA, ALIF), arrayOf(LAM, AIN)),
    J24_LA_A_NA("j24-la-'a-na", arrayOf(LAM, AIN, NUN), arrayOf(ALIF, AIN, TA), arrayOf(RA, SIN, NUN)),
    J25_LA_HA_BA("j25-la-ha-ba", arrayOf(LAM, HA, BA), arrayOf(ALIF, HA, NUN), arrayOf(ALIF, SHOD, BA)),
    J26_MA_KA_TSA("j26-ma-ka-tsa", arrayOf(MIM, KAF, TSA), arrayOf(HA, KAF, YA), arrayOf(FA, KHA, TSA)),
    J27_MA_LA_KA("j27-ma-la-ka", arrayOf(MIM, LAM, KAF), arrayOf(HA, LAM, ALIF), arrayOf(SHOD, ALIF, KAF)),
    J28_NA_JA("j28-na-ja", arrayOf(NUN, JIM), arrayOf(BA, JIM), arrayOf(KHA, GHOIN)),
    J29_NA_TA_BA("j29-na-ta-ba", arrayOf(NUN, TA, BA), arrayOf(BA, TA, NUN), arrayOf(FA, QOF, BA)),
    J30_QA_A_MA("j30-qa-a-ma", arrayOf(QOF, ALIF, MIM), arrayOf(FA, ALIF, HA), arrayOf(TA, LAM, MIM)),
    J31_SA_KHO_RA("j31-sa-kho-ra", arrayOf(SIN, KHO, RA), arrayOf(SHOD, KHO, ZA), arrayOf(HA, NUN, RA)),
    J32_SHA_LA("j32-sha-la", arrayOf(SHOD, LAM), arrayOf(DHOD, LAM), arrayOf(THO, RA)),
    J33_TSA_BA("j33-tsa-ba", arrayOf(TSA, BA), arrayOf(NUN, BA), arrayOf(SYIN, KHO)),
    J34_TSA_RA("j34-tsa-ra", arrayOf(TSA, RA), arrayOf(TA, RA), arrayOf(SYIN, YA)),
    J35_A_NA_QA("j35-'a-na-qa", arrayOf(AIN, NUN, QOF), arrayOf(GHOIN, NUN, WAWU), arrayOf(KHA, FA, QOF)),
    J36_WA_NA_A("j36-wa-na-a", arrayOf(WAWU, NUN, ALIF), arrayOf(FA, NUN, AIN), arrayOf(HA, FA, ALIF)),
    J37_YA_KHO_DHO("j37-ya-kho-dho", arrayOf(YA, KHO, DHOD), arrayOf(NUN, JIM, DHOD), arrayOf(QOF, NUN, DHOD)),
    J38_ZA_KA_A("j38-za-ka-a", arrayOf(ZA, KAF, ALIF), arrayOf(RA, KAF, AIN), arrayOf(NUN, AIN, ALIF)),
    J39_ZHA_A_DHO("j39-zha-a-dho", arrayOf(DHO, ALIF, DHOD), arrayOf(THO, ALIF, SHOD), arrayOf(DHOD, LAM, DHOD)),
    J40_ZHA_JA_RA("j40-zha-ja-ra", arrayOf(DHO, JIM, RA), arrayOf(THO, JIM, ZA), arrayOf(DHOD, ALIF, JIM, RA)),
}
