package com.github.doandadr.petualanganhijaiyah.asset

enum class Buttons(val style: String) {
    LEVEL1("level1"),
    LEVEL2("level2"),
    LEVEL3("level3"),
    LEVEL4("level4"),
    LEVEL5("level5"),
    LEVEL6("level6"),
    LEVEL7("level7"),
    LEVEL8("level8"),
    LEVEL9("level9"),
    GIRL_SELECT("girl-select"),
    BOY_SELECT("boy-select"),
    MENU("menu"),
    X("x"),
    CHECK("check"),
    HIJAIYAH("hijaiyah"),
    HIJAIYAH_DROP("hijaiyah-drop"),
    HIJAIYAH_STATE("hijaiyah-state"),
    JOIN("join"),
    JOIN_STATE("join-state")
}

enum class CheckBoxes(val style: String) {
    SOUND("sound"),
    MUSIC("music"),
}

enum class ImageButtons(val style: String) {
    BACK("back"),
    BOOK("book"),
    COIN("coin"),
    VOICE("voice"),
    MENU("menu"),
    REPEAT("repeat"),
    CANCEL("cancel"),
    NEXT("next"),
    PREVIOUS("previous"),
    X("x"),
    CHECK("check"),
    HOME("home"),
    INFO("info"),
    HINT("hint"),
    QUESTION("question"),
    SCORE("score"),
    SKIP("skip"),
}

enum class ImageTextButtons(val style: String) {
    SKIP("skip"),
    SUBMIT("submit"),
}

enum class Labels(val style: String) {
    ARABIC("arabic"),
    BANNER_GREEN("banner-green"),
    BANNER_ORANGE("banner-orange"),
    BANNER_RED("banner-red"),
    BOARD("board"),
    MAP("map"),
    PRIMARY("primary"),
    PRIMARY_BORDER("primary-wb"),
    PRIMARY_GREEN_WHITE_BORDER("primary-gw"),
    PRIMARY_GREY_WHITE_BORDER("primary-sw"),
    PRIMARY_ORANGE_WHITE_BORDER("primary-ow"),
    SECONDARY("secondary"),
    SECONDARY_BORDER("secondary-wb"),
    SECONDARY_GREEN_WHITE_BORDER("secondary-gw"),
    SIGN_NAME("sign-name"),
    TEXTBOX_BLUE_ROUNDED("textbox-blue-rounded"),
    TEXTBOX_GREEN_SQUARE_LARGE("textbox-green-square-large"),
    TEXTBOX_ORANGE_ROUNDED("textbox-orange-rounded"),
    TEXTBOX_ORANGE_SQUARE_LARGE("textbox-orange-square-large"),
    TEXTBOX_WHITE_SQUARE_LARGE("textbox-white-square-large"),
    TEXTBOX_WHITE_SQUARE_SMALL("textbox-white-square-small"),
    TIMER_COUNTER("timer-counter"),
    TUTORIAL_LEFT_DOWN("tutorial-left-down"),
    TUTORIAL_LEFT_UP("tutorial-left-up"),
    TUTORIAL_RIGHT_DOWN("tutorial-right-down"),
    TUTORIAL_RIGHT_UP("tutorial-right-up"),
    BUBBLE("bubble"),
}

enum class TextButtons(val style: String) {
    BOARD("board"),
    SIGN("sign"),
    GREEN_LARGE("green-large"),
    GREEN_SMALL("green-small"),
    ORANGE_LARGE("orange-large"),
    ORANGE_SMALL("orange-small"),
}

enum class Drawables(val drawable: String) {
    BISMILLAH("bismillah"),
    BISMILLAH_WHITE("bismillah-white"),
    BOOK("book"),
    BOX_WHITE_ROUNDED("box-rounded"),
    BOX_ORANGE_ROUNDED("box-orange-rounded"),
    BOY("boy"),
    BOY_SELECT("boy-select"),
    CHECKERED_FLAG("checkered-flag"),
    CIRCLE_GREEN("circle-green"),
    CIRCLE_GREY("circle-grey"),
    CIRCLE_ORANGE("circle-orange"),
    CIRCLE_BRUSH("circle-brush"),
    EFFECT_CONFETTI("confetti"),
    EFFECT_SALUTE("salute"),
    EFFECT_SMALL_FIREWORK("small-firework"),
    GIRL("girl"),
    GIRL_2("girl-2"),
    GIRL_SELECT("girl-select"),
    HAND_POINTING("hand-pointing"),
    HIJAIYAH_FRAME_LARGE("hijaiyah-frame-large"),
    ICON_AUDIO("icon-audio"),
    ICON_AUDIOOFF("icon-audiooff"),
    ICON_CLOCK("icon-clock"),
    ICON_COIN("icon-coin"),
    ICON_BOOK("icon-book"),
    ICON_DIAMOND("icon-diamond"),
    ICON_HEART_EMPTY("icon-heartempty"),
    ICON_HEART_FULL("icon-heartfull"),
    ICON_HEART_HALF("icon-hearthalf"),
    ICON_LOCK("icon-lock"),
    ICON_LOOKING_GLASS("icon-looking-glass"),
    ICON_PRIZE("icon-prize"),
    ICON_STAR_LARGE("icon-star-large"),
    ICON_STAR_MEDIUM("icon-star-medium"),
    ICON_STAR_SMALL("icon-star-small"),
    ICON_STARGREY_LARGE("icon-stargrey-large"),
    ICON_STARGREY_MEDIUM("icon-stargrey-medium"),
    ICON_STARGREY_SMALL("icon-stargrey-small"),
    ICONBUTTON_WHITE_ROUNDED("iconbutton-white-rounded"),
    ICONBUTTON_BACKGROUND_ROUNDED("iconbutton-background-rounded"),
    LEVEL_FINISH_STARBOX("level-finish-starbox"),
    TIMER_BACKGROUND_EMPTY("timer-background-empty"),
    TIMER_BACKGROUND_GREEN("timer-background-green"),
    TIMER_COUNTER_DOTS("timer-counter-dots"),
    TIMER_FRAME_ORANGE("timer-frame-orange"),
    TIMER_FRAME_WHITE("timer-frame-white"),
    LINE("line"),
    SIGN("sign"),
    SIGN_SHARP("sign-sharp"),
    SPEECH_BUBBLE("speech-bubble"),
}

enum class Colors(val color: String) {
    BLACK("RGBA_0_0_0_255"),
    WHITE("RGBA_255_255_255_255"),
    YELLOW_OLD("RGBA_255_187_0_255"),
    GREEN_OLD("RGBA_88_129_87_255"),
    BLUE("RGBA_0_126_224_255"),
    RED("RGBA_220_0_62_255"),
    ORANGE("RGBA_232_110_0_255"),
    GREEN("RGBA_45_165_0_255"),
    LIGHT_GREEN("RGBA_170_255_136_255"),
    GREY("RGBA_94_105_126_255"),
    BROWN("RGBA_164_77_0_255"),
}

